//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetCommander.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1, -1")]
        public global::System.Drawing.Point WindowStartPos {
            get {
                return ((global::System.Drawing.Point)(this["WindowStartPos"]));
            }
            set {
                this["WindowStartPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800, 600")]
        public global::System.Drawing.Size WindowStartSize {
            get {
                return ((global::System.Drawing.Size)(this["WindowStartSize"]));
            }
            set {
                this["WindowStartSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WindowStartMaximized {
            get {
                return ((bool)(this["WindowStartMaximized"]));
            }
            set {
                this["WindowStartMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\")]
        public string LeftBrowserLastPath {
            get {
                return ((string)(this["LeftBrowserLastPath"]));
            }
            set {
                this["LeftBrowserLastPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\")]
        public string RightBrowserLastPath {
            get {
                return ((string)(this["RightBrowserLastPath"]));
            }
            set {
                this["RightBrowserLastPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LeftBrowserDrivePaths {
            get {
                return ((string)(this["LeftBrowserDrivePaths"]));
            }
            set {
                this["LeftBrowserDrivePaths"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RightBrowserDrivePaths {
            get {
                return ((string)(this["RightBrowserDrivePaths"]));
            }
            set {
                this["RightBrowserDrivePaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QuickViewCsvEnabled {
            get {
                return ((bool)(this["QuickViewCsvEnabled"]));
            }
            set {
                this["QuickViewCsvEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5242880")]
        public int QuickViewCsvMaxBytes {
            get {
                return ((int)(this["QuickViewCsvMaxBytes"]));
            }
            set {
                this["QuickViewCsvMaxBytes"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("262144")]
        public int QuickViewTextMaxBytes {
            get {
                return ((int)(this["QuickViewTextMaxBytes"]));
            }
            set {
                this["QuickViewTextMaxBytes"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif")]
        public string BrowserFontName {
            get {
                return ((string)(this["BrowserFontName"]));
            }
            set {
                this["BrowserFontName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11.25")]
        public float BrowserFontSize {
            get {
                return ((float)(this["BrowserFontSize"]));
            }
            set {
                this["BrowserFontSize"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string BrowserRowColorMode {
            get {
                return ((string)(this["BrowserRowColorMode"]));
            }
            set {
                this["BrowserRowColorMode"] = value;
            }
        }


        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI")]
        public string DialogFontName {
            get {
                return ((string)(this["DialogFontName"]));
            }
            set {
                this["DialogFontName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public float DialogFontSize {
            get {
                return ((float)(this["DialogFontSize"]));
            }
            set {
                this["DialogFontSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public float DialogCaptionFontSize {
            get {
                return ((float)(this["DialogCaptionFontSize"]));
            }
            set {
                this["DialogCaptionFontSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public float DialogEmphasisFontSize {
            get {
                return ((float)(this["DialogEmphasisFontSize"]));
            }
            set {
                this["DialogEmphasisFontSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public float DialogHeaderFontSize {
            get {
                return ((float)(this["DialogHeaderFontSize"]));
            }
            set {
                this["DialogHeaderFontSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Consolas")]
        public string TextEditorFontName {
            get {
                return ((string)(this["TextEditorFontName"]));
            }
            set {
                this["TextEditorFontName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public float TextEditorFontSize {
            get {
                return ((float)(this["TextEditorFontSize"]));
            }
            set {
                this["TextEditorFontSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TextEditorWordWrap {
            get {
                return ((bool)(this["TextEditorWordWrap"]));
            }
            set {
                this["TextEditorWordWrap"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowStatusHints {
            get {
                return ((bool)(this["ShowStatusHints"]));
            }
            set {
                this["ShowStatusHints"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowEditorStatusBar {
            get {
                return ((bool)(this["ShowEditorStatusBar"]));
            }
            set {
                this["ShowEditorStatusBar"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OverwriteExistingFiles {
            get {
                return ((bool)(this["OverwriteExistingFiles"]));
            }
            set {
                this["OverwriteExistingFiles"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenCreatedFolderAfterCreate {
            get {
                return ((bool)(this["OpenCreatedFolderAfterCreate"]));
            }
            set {
                this["OpenCreatedFolderAfterCreate"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI")]
        public string RtfEditorFontName {
            get {
                return ((string)(this["RtfEditorFontName"]));
            }
            set {
                this["RtfEditorFontName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public float RtfEditorFontSize {
            get {
                return ((float)(this["RtfEditorFontSize"]));
            }
            set {
                this["RtfEditorFontSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI")]
        public string MarkdownPreviewFontName {
            get {
                return ((string)(this["MarkdownPreviewFontName"]));
            }
            set {
                this["MarkdownPreviewFontName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Consolas")]
        public string MarkdownPreviewCodeFontName {
            get {
                return ((string)(this["MarkdownPreviewCodeFontName"]));
            }
            set {
                this["MarkdownPreviewCodeFontName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int MarkdownPreviewBaseFontSize {
            get {
                return ((int)(this["MarkdownPreviewBaseFontSize"]));
            }
            set {
                this["MarkdownPreviewBaseFontSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int MarkdownPreviewH1FontSize {
            get {
                return ((int)(this["MarkdownPreviewH1FontSize"]));
            }
            set {
                this["MarkdownPreviewH1FontSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public int MarkdownPreviewH2FontSize {
            get {
                return ((int)(this["MarkdownPreviewH2FontSize"]));
            }
            set {
                this["MarkdownPreviewH2FontSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int MarkdownPreviewH3FontSize {
            get {
                return ((int)(this["MarkdownPreviewH3FontSize"]));
            }
            set {
                this["MarkdownPreviewH3FontSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int MarkdownPreviewH4FontSize {
            get {
                return ((int)(this["MarkdownPreviewH4FontSize"]));
            }
            set {
                this["MarkdownPreviewH4FontSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MarkdownPreviewH5FontSize {
            get {
                return ((int)(this["MarkdownPreviewH5FontSize"]));
            }
            set {
                this["MarkdownPreviewH5FontSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int MarkdownPreviewH6FontSize {
            get {
                return ((int)(this["MarkdownPreviewH6FontSize"]));
            }
            set {
                this["MarkdownPreviewH6FontSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MarkdownPreviewRerenderOnResize {
            get {
                return ((bool)(this["MarkdownPreviewRerenderOnResize"]));
            }
            set {
                this["MarkdownPreviewRerenderOnResize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int FileBrowserNameColumnWidth {
            get {
                return ((int)(this["FileBrowserNameColumnWidth"]));
            }
            set {
                this["FileBrowserNameColumnWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int FileBrowserTypeColumnWidth {
            get {
                return ((int)(this["FileBrowserTypeColumnWidth"]));
            }
            set {
                this["FileBrowserTypeColumnWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int FileBrowserSizeColumnWidth {
            get {
                return ((int)(this["FileBrowserSizeColumnWidth"]));
            }
            set {
                this["FileBrowserSizeColumnWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int FileBrowserDateColumnWidth {
            get {
                return ((int)(this["FileBrowserDateColumnWidth"]));
            }
            set {
                this["FileBrowserDateColumnWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FileBrowserDirectoriesFirst {
            get {
                return ((bool)(this["FileBrowserDirectoriesFirst"]));
            }
            set {
                this["FileBrowserDirectoriesFirst"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FileBrowserLoadIcons {
            get {
                return ((bool)(this["FileBrowserLoadIcons"]));
            }
            set {
                this["FileBrowserLoadIcons"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FileBrowserLoadLargeIcons {
            get {
                return ((bool)(this["FileBrowserLoadLargeIcons"]));
            }
            set {
                this["FileBrowserLoadLargeIcons"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FileBrowserWatchDirectoryChanges {
            get {
                return ((bool)(this["FileBrowserWatchDirectoryChanges"]));
            }
            set {
                this["FileBrowserWatchDirectoryChanges"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:11434")]
        public string AiOrganizerEndpoint {
            get {
                return ((string)(this["AiOrganizerEndpoint"]));
            }
            set {
                this["AiOrganizerEndpoint"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("qwen3.5:latest")]
        public string AiOrganizerModel {
            get {
                return ((string)(this["AiOrganizerModel"]));
            }
            set {
                this["AiOrganizerModel"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("embeddinggemma:latest")]
        public string AiEmbeddingModel {
            get { return ((string)(this["AiEmbeddingModel"])); }
            set { this["AiEmbeddingModel"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:11434")]
        public string AiEmbeddingEndpoint {
            get { return ((string)(this["AiEmbeddingEndpoint"])); }
            set { this["AiEmbeddingEndpoint"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VectorStoreBasePath {
            get { return ((string)(this["VectorStoreBasePath"])); }
            set { this["VectorStoreBasePath"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VectorIndexTextEnabled {
            get { return ((bool)(this["VectorIndexTextEnabled"])); }
            set { this["VectorIndexTextEnabled"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VectorIndexMarkdownEnabled {
            get { return ((bool)(this["VectorIndexMarkdownEnabled"])); }
            set { this["VectorIndexMarkdownEnabled"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VectorIndexCsvEnabled {
            get { return ((bool)(this["VectorIndexCsvEnabled"])); }
            set { this["VectorIndexCsvEnabled"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int VectorIndexChunkSizeCharacters {
            get { return ((int)(this["VectorIndexChunkSizeCharacters"])); }
            set { this["VectorIndexChunkSizeCharacters"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int VectorIndexChunkOverlapCharacters {
            get { return ((int)(this["VectorIndexChunkOverlapCharacters"])); }
            set { this["VectorIndexChunkOverlapCharacters"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int VectorIndexMaxFileSizeMb {
            get { return ((int)(this["VectorIndexMaxFileSizeMb"])); }
            set { this["VectorIndexMaxFileSizeMb"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2048")]
        public int VectorIndexMaxStoreSizeMb {
            get { return ((int)(this["VectorIndexMaxStoreSizeMb"])); }
            set { this["VectorIndexMaxStoreSizeMb"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int AiOrganizerMaxFileCount {
            get {
                return ((int)(this["AiOrganizerMaxFileCount"]));
            }
            set {
                this["AiOrganizerMaxFileCount"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int AiOrganizerBatchSize {
            get {
                return ((int)(this["AiOrganizerBatchSize"]));
            }
            set {
                this["AiOrganizerBatchSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("auto")]
        public string AiOrganizerContextMode {
            get {
                return ((string)(this["AiOrganizerContextMode"]));
            }
            set {
                this["AiOrganizerContextMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4096")]
        public int AiOrganizerMaxTextCharactersPerFile {
            get {
                return ((int)(this["AiOrganizerMaxTextCharactersPerFile"]));
            }
            set {
                this["AiOrganizerMaxTextCharactersPerFile"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65536")]
        public int AiOrganizerMaxTotalTextCharacters {
            get {
                return ((int)(this["AiOrganizerMaxTotalTextCharacters"]));
            }
            set {
                this["AiOrganizerMaxTotalTextCharacters"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("auto")]
        public string UiLanguage {
            get {
                return ((string)(this["UiLanguage"]));
            }
            set {
                this["UiLanguage"] = value;
            }
        }
    }
}
